elementary/terminal

data/pantheon-terminal.appdata.xml.in
Just a couple of things I noticed
=> Clean up appdata

src/PantheonTerminalWindow.vala
* Don't use this
* Organize
* Don't set extra style class
* use properties
=> PantheonTerminalWindow.vala: misc cleanups

src/PantheonTerminalWindow.vala, src/Widgets/TerminalWidget.vala
Fixes #150 
In my previous pull request (#125), the behavior of the middle button was like in Windows (pasting clipboard). Now I did the behavior of middle mouse button like GTK and Linux (copying and pasting from primary selection).
=> Correct behavior of middle button (#150)

src/PantheonTerminalWindow.vala
Fixes https://github.com/elementary/stylesheet/issues/210
=> Fix light bleed on maximized Terminal windows

src/PantheonTerminalWindow.vala, src/Widgets/TerminalWidget.vala
It is not valid and causes warnings during compilation.
=> Remove static modifier from constants

data/io.elementary.terminal.gschema.xml, src/PantheonTerminalWindow.vala, src/Settings.vala, src/Widgets/TerminalWidget.vala
This stores the last set zoom factor into SavedState and restores it upon opening a new terminal (tab or window.)
Fixes #143
=> Restore zoom level from saved state

data/Application.css
CSS doesn't support single line comments, nor is it Vala.
=> Remove Vala header from CSS file

src/Widgets/SearchToolbar.vala
=> Add a button to set cyclic search

src/PantheonTerminalWindow.vala
=> Set is_fullscreen when restoring fullscreen

src/Constants.vala, src/DBus.vala, src/PantheonTerminalWindow.vala, src/Settings.vala, src/Widgets/TerminalWidget.vala
=> Update license headers

src/Application.vala
This corrects behavior when opening a directory and then trying to open a new window.
Edit: Also fixes the same problem from print_version
Fixes #41  
Fixes #111
=> Reset argument values after handling

src/PantheonTerminalWindow.vala
=> Move menu button to end and use open-menu

src/PantheonTerminalWindow.vala
=> Explicitly declare menuitems as translatable

src/PantheonTerminalWindow.vala, src/Widgets/SearchToolbar.vala
Ports Jeremy's changes from #254
=> Add search next and previous to actions

src/PantheonTerminalWindow.vala, src/Widgets/TerminalWidget.vala
=> Simplify zoom

src/Application.vala, src/PantheonTerminalWindow.vala, src/Widgets/TerminalWidget.vala
Also get rid of the unnecessary `namespace PantheonTerminal` here. No other changes
=> Rename PantheonTerminalApp to TerminalApp

.travis.yml
=> Test using Houston CI

README.md, meson.build, src/PantheonTerminalWindow.vala, src/Widgets/SearchToolbar.vala
The way the search toggle is handled here isn't as nice as the way it's done in Code, so sometimes the tooltip isn't updated there. I think fixing that mechanism is probably outside the scope of this branch though
=> Adds accels to tooltip markup

src/PantheonTerminalWindow.vala
=> PantheonTerminalWindow: Fix invalid action names

src/Dialogs/UnsafePasteDialog.vala
Subclass Granite.MessageDialog instead of Gtk.Dialog
=> UnsafePasteDialog: Use GraniteMessageDialog

data/io.elementary.terminal.gschema.xml
=> Set bell to false by default, add description

meson.build, po/POTFILES, src/Application.vala, src/Dialogs/ForegroundProcessDialog.vala, src/Dialogs/UnsafePasteDialog.vala, src/MainWindow.vala, src/Widgets/SearchToolbar.vala, src/Widgets/TerminalWidget.vala
=> Rename PantheonTerminalWindow to MainWindow

src/Widgets/TerminalWidget.vala
=> Set pointer_autohide property to true

src/MainWindow.vala
~Trying to fix https://github.com/elementary/terminal/issues/368. This also (usually) segfaults, just like https://github.com/elementary/code/pull/661~
Fixes #368
=> Zoom with Ctrl+Equal

src/MainWindow.vala
=> Pressing the menu keyboard button opens right-click menu

data/io.elementary.terminal.gschema.xml, src/Application.vala, src/MainWindow.vala, src/Settings.vala, src/Widgets/TerminalWidget.vala
While we're here, modernize saved state settings to use fewer keys
Fixes #15 
Fixes #377
=> Use GSettings for Saved State

src/MainWindow.vala
=> MainWindow: Add accels to menuitem labels

src/Application.vala, src/DBus.vala, src/Dialogs/ForegroundProcessDialog.vala, src/Dialogs/UnsafePasteDialog.vala, src/MainWindow.vala, src/Settings.vala, src/Widgets/SearchToolbar.vala, src/Widgets/TerminalWidget.vala
=> Change PantheonTerminal.TerminalApp to Terminal.Application

src/MainWindow.vala
Also remove unused `main_actions` and explicitly scope methods
=> MainWindow: Reduce method scope and remove unused methods

src/Widgets/TerminalWidget.vala
- reintroduce: Turn off blink till button_release_event
- remove unneeded integer casts
- rename some variables for clarity reasons
=> move only relative if clicked below last click

src/MainWindow.vala
=> Add duplicate tab shortcut.

data/io.elementary.terminal.appdata.xml.in, src/MainWindow.vala, src/Widgets/TerminalWidget.vala
=> Ctrl scroll zoom

data/io.elementary.terminal.appdata.xml.in, src/Application.vala, src/MainWindow.vala
Fixes https://github.com/elementary/terminal/issues/283
=> MainWindow: Apply font changes on the fly

src/MainWindow.vala
=> Ensure at least one tab in new window; ensure correct tab label

po/extra/meson.build, po/meson.build
=> Fix auto po file generation

src/DBus.vala, src/Widgets/TerminalWidget.vala
Two commits that bring tiny fixes
=> Several fixes to the terminal

meson.build, src/Widgets/TerminalWidget.vala
=> vte-2.91: Adapt to latest changes in version 0.60

data/io.elementary.terminal.appdata.xml.in, src/Widgets/TerminalWidget.vala
=> Validate colors restored from settings; correct and replace as required.

README.md, meson.build, src/MainWindow.vala
Fixes window dragging with the latest Handy
=> MainWindow: Use Hdy.HeaderBar and Hdy.init

data/Application.css
This fixes some stuff in the dark style. setting "background" overrides some properties we want to set differently here
=> Application.css: Fix color button sharpness

po/extra/es.po, src/MainWindow.vala
=> Ctrl+tab key bind: go to previous tab

data/io.elementary.terminal.appdata.xml.in
Should have done this before merging last commit :disappointed:
=> Update next release appdata re new shortcuts

data/Application.css
Since that's our standard window padding
=> Application.css: increase padding

src/MainWindow.vala, src/Widgets/TerminalWidget.vala
MainWindow: Simplify the flags check
=> TerminalWidget: fix copy not working on the first try

src/Dialogs/UnsafePasteDialog.vala, src/MainWindow.vala
=> Add text to paste in details pane for UnsafePasteDialog.

README.md, meson.build, src/MainWindow.vala
As title implies. There's some other deprecations that I'd like to check out but perhaps in a separate PR.
=> Use Granite.SwitchModelButton

src/Dialogs/UnsafePasteDialog.vala, src/MainWindow.vala
So we can actually tell what this conditional is in MainWindow
=> UnsafePasteDialog: Use Gtk.ResponseType

src/Dialogs/ForegroundProcessDialog.vala, src/Widgets/TerminalWidget.vala
=> Add dialog to reload tab action if there is a foreground process

.github/workflows/ci.yml
Only run CI actions on PR. Update to checkout@v2
=> Actions: only run CI on PR

src/MainWindow.vala
The first commit replace single character variable names with more verbose name. I used the vala-language server for rename to make sure nothing gets messed up.
The second commit initializes object with properties. I used the script from https://github.com/elementary/gala/pull/965
=> Code Style MainWindow.vala: More verbose variable names & Initialize Objects with Properties 

src/Dialogs/UnsafePasteDialog.vala, src/MainWindow.vala
This gets rid of some warning messages during compilation.
=> Replace some deprecated functions

src/Application.vala
=> Application: set notification icon badges

src/MainWindow.vala
There was no opportunity to close terminal using hotkeys. I've fixed it and added option to quit with ctrl + shitf + q
=> Added hotkey to close terminal

data/Application.css, data/io.elementary.terminal.gschema.xml, meson.build, src/Application.vala, src/MainWindow.vala, src/Themes.vala
Part of #552, in preparation for providing a custom theme dialog.
This PR should make no change in the appearance or functionality of theme selection.
=> Simplify handling of themes

src/Dialogs/ColorPreferencesDialog.vala, src/Themes.vala
Seems a bit more straightforward and deterministic?
=> Dialogs/ColorPreferences: reset to default via gsettings

README.md, data/io.elementary.terminal.gschema.xml, meson.build, src/Widgets/SearchToolbar.vala, src/Widgets/TerminalWidget.vala
Drop support for old VTE. Focal has 0.60
=> Require libvte >=0.59

src/MainWindow.vala
=> MainWindow: Update context menu on menu key press

.github/workflows/ci.yml, src/meson.build
Allows to test it in headless environments (ci, PPAs…)
=> meson: Specify default test setup

data/io.elementary.terminal.1, data/meson.build
Needs consideration of what to do about deb-packaging and old compressed man file that will be present and take precedence on systems where Terminal has already been installed.
=> Install man page with meson

debian/io.elementary.terminal.install
=> Reinstate io.elementary.terminal.install

data/io.elementary.terminal.gschema.xml, src/MainWindow.vala
GTK 4/Wayland prep. Can't set window position in Wayland
=> Remove window position

src/Widgets/SearchToolbar.vala, src/Widgets/SettingsPopover.vala
GTK4 prep. This defaults to 16px already
=> Don't set icon size for button from icon name

data/Application.css, src/MainWindow.vala, src/Widgets/ZoomOverlay.vala
I was poking at this and wondered, why aren't we using an overlaybar here?
=> Use Granite.Overlaybar

src/Widgets/TerminalWidget.vala
Doas is also a program used to gain administrative access so I thought I would add it here just to cover all corners.
=> upd(TerminalWidget): add doas checking

src/Application.vala
=> Application: withdraw stale notifications

meson.build
Bumped to 7 because we're no longer releasing Terminal on OS 6
=> Release 7.0.0

src/Utils.vala, src/tests/UnsafePasteTest.vala
As suggested in https://github.com/elementary/terminal/pull/864#pullrequestreview-2727980557
=> UnsafePaste: add -f and --force

data/io.elementary.terminal.appdata.xml.in
Target release date 8th August 2025
=> Prepare for release 7.1.0
