elementary/terminal

- src/PantheonTerminalWindow.vala
The output of process may be studied after the process ends.
See #7
> Do not close the terminal window when a child process exits normally.

- src/TerminalWidget.vala
This should address issue #80 regarding the deprecated `match_check()`.
> Replace deprecated `Vte.Terminal.match_check()` 

- src/PantheonTerminalWindow.vala
Nullify 'program' variable after program exits so next "child-exited" signal from terminal closes the tab.
Fixes #91
> Allow tab to close after typing 'exit' at the commandline.

- src/PantheonTerminalWindow.vala
This replaces an elementary-specific style class with a class used by Gtk itself. There should be no visible difference.
The purpose of this class is to reduce the padding in Terminal's headerbar
> Replace compact class with default-decoration

- src/PantheonTerminalWindow.vala
This wording is more consistent with Photos and Music and doesn't assume the name of the file browser
> Change Open in Files to Show in File Browser

- data/org.pantheon.terminal.desktop.in
- src/PantheonTerminal.vala
After #115 all of the information here will be present on Terminal's AppInfo page in AppCenter. No need for this dialog anymore
> kill the about dialog

- src/PantheonTerminalWindow.vala
This disables Gtk from handling F10 key itself so that other widgets can further receive the event.
The solution itself wasn't found by me, I just searched "F10" in VTE's source code and found this:
https://github.com/GNOME/vte/blob/c9e7cbabfe2fd682a80dd8938c317e7aed1195f4/src/vteapp.c#L897.
We don't use any menus, while e.g: GNOME's Terminal does use menu and pressing F10 does trigger opening the menu there, but prevents from receiving the event by the terminal itself.
> Disable handling F10 key by Gtk itself

- src/UnsafePasteDialog.vala
Fixes #127. Adds an option to not show this dialog again. Please correct the label in diff comments if it isn't right.
> Add a check for unsafe paste dialog

- src/UnsafePasteDialog.vala
Rewrite as a HIG-compliant Gtk.Dialog
* GObject-style construction
* Update license header
* Don't use namespace
Before:
After:
> Rewrite Unsafe Paste Dialog as Gtk.Dialog

- CMakeLists.txt
- src/Application.vala
* Rename to be in line with naming from other repos and make the app class easy to find
* Update license header
* static is not applicable to constants
> Move PantheonTerminal.vala to Application.vala

- src/Widgets/SearchToolbar.vala
* GObject-style construction
* Update copyright header
* Use lambdas for methods that don't get re-used
* Reduce variable scope
* Don't create variables when unnecessary 
* Don't use `this`
* Make `clear ()` a public method instead of a signal
> rewrite SearchToolbar.vala

- src/PantheonTerminalWindow.vala
Port only accelerators over to GLib.Action. Don't port anything in the context menu.
This is a portion of the work from #146 that doesn't appear to cause any regression
> Port accelerators over to GLib.action

- src/PantheonTerminalWindow.vala
- src/Widgets/TerminalWidget.vala
Fixes #154.
This issue is caused by a signal that Terminal relies on not being emitted from Vte.Terminal when the .bashrc does not force setting of the window title. There appears to be no simple way to fix this in Terminal so this branch simply avoids having any blank tabs or titles under these circumstances (all labelled "Terminal").
> Tab label and window title fallback to "Terminal" rather than blank.

- data/io.elementary.terminal.gschema.xml
- src/PantheonTerminalWindow.vala
- src/Settings.vala
- src/Widgets/TerminalWidget.vala
Adds a setting for Dark/Light/High Contrast style Fixes #147
* Reformatted the hex_palette array and use colors from default gsettings
* Added a setting for gtk_prefer_dark and restore it on app startup
* Set prefer_dark, foreground, and background colors from the popover
> Dark light settings

- src/Widgets/SearchToolbar.vala
This branch is meant to bring the behavior of the findbar in Terminal more in line with the findbar in Code:
* Hexpand the search entry
* Put buttons in a linked container
* Put buttons in the same order as Code
* Only make next and previous buttons sensitive when the entry has text in it
> Findbar tweaks

- src/PantheonTerminalWindow.vala
> PantheonTerminalWindow.vala: make Gdk.Atom nullable

- src/Application.vala
- src/PantheonTerminalWindow.vala
Restores tabs when opening Terminal with a directory, this tab however would not gain focus as tab restores are done at full idle. To ensure the tab correctly grabs focus the tab restore and subsequently create functions had to be modified so they had a parameter to define whether they would grab focus.
Fixes #62
> Restore tabs when starting with a directory

- src/PantheonTerminalWindow.vala
* make `app`, `restore_pos`, and `recreate_tabs` public properties
* Sort public and private variables
* Use `Object` instead of passing vars to `init`
* Combine `init` and `construct`
> PantheonTerminalWindow.vala: make constructor properties public

- src/PantheonTerminalWindow.vala
* Use the `action_name` property instead of connect to `button.clicked`
* Add an action for zoom default
* Use action accels for keypad zoom shortcuts
> Add keypad shortcuts, use action_name

- data/io.elementary.terminal.gschema.xml
- src/PantheonTerminalWindow.vala
- src/Settings.vala
Adds a new key to save to index of the focused tab so that when restoring tabs it will be focused to the correct tab (if the tabs are set to restore focus.)
Fixes #12
> Restore tab focus

- src/PantheonTerminalWindow.vala
This call could not actually be removed without breaking behaviour. This ensures the last closed terminal window is saved rather than the last active.
> Save tabs when terminal is closed

- src/Application.vala
- src/PantheonTerminalWindow.vala
When creating a new window with coord it always attempted to create a tab if none existed (from #189) as no tab existing breaks the window, this adds a parameter to not ensure this, for if a tab will be created later.
Fixes #199
> Allow not ensuring tab existence for new window with coord

- po/CMakeLists.txt
Make pot command didn't work, this updates the file names of the desktop files to correct this.
> Fix make pot command

- src/PantheonTerminalWindow.vala
The tab was being focused not the terminal widget.
Fixes #203
> Grab focus to terminal widget when restoring

- data/io.elementary.terminal.gschema.xml
Running `glib-compile-schemas --strict` revealed that there were two `<description>` nodes in some of the schema keys.
This branch removes the shorter description for the background and cursor-color keys, and makes the gschema file syntactically correct.
> Remove duplicate descriptions

- src/Application.vala
Do not set notification ID so that several notifications about process completion can coexist. Fixes #221
Reference: https://valadoc.org/gio-2.0/GLib.Application.send_notification.html
> Allow several completion notifications to coexist

- data/io.elementary.terminal.desktop.in
These icons show in plank and they don't really add anything here. It looks silly to have the same two icons for both actions
> Remove icons from .desktop actions

- src/Application.vala
`Granite.Application` is deprecated so let's switch to `Gtk.Application`
Just a quick one line change as this doesn't seem to break anything, let me know if there's anything I need to add.
> update to Gtk.Application

- src/Application.vala
Fixes #233
with respect to opening second window from Plank.
The application_id is set to ensure only one instance of the application is run, fixing regression caused by #229
> Do not restore tabs in new window from Plank.

- data/Application.css
Because of rounded corners in tiles now and light bleed in those corners
> Make Terminal opaque when tiled

- README.md
- data/meson.build
- data/pantheon_terminal_process_completion_notifications.fish
- Update FISH integration to new D-bus API (#214)
- Put the post-exec hook in a designated directory for vendor config, so the user no longer has to edit any config files to get it to work. Vendor config is available starting with FISH version 2.3; Juno ships with 2.7
> Update FISH integration for the new D-bus API and enable it by default

- src/PantheonTerminalWindow.vala
Fixed typo in Accelerators, causing Shift+A to be interpreted as Select All, Also fixed Missing Bracket on Paste.
> Fix Typos causing Keyboard Issues

- src/PantheonTerminalWindow.vala
We don't need this in elementary OS because Gala centers windows by default, but this at least removes some unnecessary witchcraft without changing functionality for other DEs
> Window: Remove centering witchcraft

- src/Application.vala
Fixes #281 
`present` is for bringing an already open window to the front, the window manager and the rest of the Gtk stack should be capable of bringing brand new application windows to the front.
> Remove present() calls from new windows

- src/PantheonTerminalWindow.vala
I was struggling with this for a while, finally found the cause today.
Quote from docs (https://developer.gnome.org/gtk3/stable/GtkHeaderBar.html#gtk-header-bar-set-subtitle):
> Note that GtkHeaderBar by default reserves room for the subtitle, even if none is currently set. If this is not desired, set the “has-subtitle” property to FALSE.
Subtitle isn't used anywhere in Terminal, so this shouldn't break anything.
> Reduce headerbar height by disabling subtitle

- data/enable-zsh-completion-notifications
The zsh process completion notification script does not work with the latest version of the app due to the exit code not being passed. This PR fixes this issue in the integration script.
For compatibility the integration script now appends the pre-command function to the existing list.
This resolves issue #244
> Fix zsh process completion notification integration

- data/io.elementary.terminal.gschema.xml
Not sure why this is false by default. True would make it consistent with other Gtk.Editables and there is already a setting in System Settings -> Sound to disable the system bell.
Not sure if this should be a setting for Terminal at all, tbh. I dunno why you'd want to disable the bell for only one app
> gschema: Make system bell default to true

- src/PantheonTerminalWindow.vala
Fixes #327 
Makes the search action a boolean and binds the search button to the search action instead of connecting to the toggle signal.
> PantheonTerminalWindow: Make search action a boolean

- src/Widgets/SearchToolbar.vala
When you use the search, whenever you type a new character it jumps to the next occurrence.
This is the previous behaviour:
The new one:
> Fix search jumping behaviour

- src/Application.vala
Proposed fix for issues #205 , #282 , and #314 . 
Implements the "-h" & "--help" option flags to show application help overriding the default exit behaviour to keep existing terminals open.
> Add option "-h" to show application help

- meson.build
This is necessary because terminal uses Gee directly, and granite built with
meson is more conservative with the linker flags it includes.
See: src/MainWindow.vala#L75
> meson: add missing 'gee-0.8' dependency

- src/MainWindow.vala
Fixes #367.
Caused by https://github.com/elementary/terminal/commit/618cf0509b93fe5bdca4ac0c1cbf4eb68b1199ff. Changed the response code for closing individual tabs but didn't change the response code for closing the terminal window.
> Fix response code being wrong in another place

- src/MainWindow.vala
This really helps once the menu is a little more busy with accel labels. I drew the separator here because these actions are all about manipulating text until we get to find and open files. I guess Find could arguably be about manipulating text, so I wouldn't argue to strongly if others felt it was better just separating the last item
> MainWindow: Add a separator to right click menu

- src/MainWindow.vala
- src/Widgets/TerminalWidget.vala
There seems to be no reason for terminal to handle middle-click if it is intended that the mouse-touchpad setting plug should be honored.
After removing this code, middle-click will paste the current selection (either inside Terminal or in another app eg.g Code) only if the mouse-touchpad setting "Middle Click Paste" is `true`.  This then matches the behaviour of Code.
Note that this depends on xsettings override being supported which is true for elementary but may not be true for another OS.  If this is a problem, it may be desirable to fallback to middle-click-paste?
> Remove unnecessary handling of middle-click.

- data/Application.css
- data/io.elementary.terminal.gschema.xml
- src/MainWindow.vala
Better matches https://github.com/elementary/stylesheet/pull/510, plus better contrast.
Fixes #373
> Use palette colors for default bg/fg

- data/Application.css
- src/MainWindow.vala
Terminal windows only have 1px of padding for their content, unlike other elementary apps:
This PR adds 3px to the horizontal padding, which is subtle, but noticeable:
Adding more than that feels like there should be vertical padding as well, but vertical padding is trickier, since the terminal window scrolls vertically.
What do you think? (Mostly from a UI perspective. The code isn't great; if I understand things correctly, we should open a PR on the VTE project to fix their internal CSS priority, and then it could be done without the +1 priority hack.)
> Add horizontal padding

- data/io.elementary.terminal.gschema.xml
> GSchema: Fix default foreground color

- data/meson.build
It looks like newer appstream is trying to validate URLs and Launchpad is failing to build because of it.
If we want to use appstream-cli we should probably do that as part of CI and not in the repo like this
> Don't access network during appstream validate

- src/MainWindow.vala
With the new changes from 2df52a9c334be97e702793bc6938c50f1e668251 it is now impossible to start the terminal with a command of already open tab:
```
io.elementary.terminal -e ls -w /tmp
```
If there is already a tab with the path of /tmp then such tab is activated and no command is run. Hence we have a new bug.
This commit makes it possible to run such commands in a working directory which has already a tab open.
> -e execute skips active tabs search

- src/Application.vala
- src/MainWindow.vala
With the new behavior of the terminal trying to match existing tab's path it is impossible to open a new tab with such existing path (working directory option -w).
- Suppose you have the terminal app open with the tab of location /tmp (running some command or simply waiting)
- Now you want to open another instance of the same path using:
```
io.elementary.terminal -w /tmp
```
This will simply activate the existing tab and nothing else will happen. Hence we cannot achieve the desired resuilt.
A new "-t" option to force a tab creation is the right solution (just lke we have for a new window).
This PR introduces the new option.
Newly, you can open the terminal with:
```
io.elementary.terminal -t -w /tmp
```
> Support for new "-t" option (create new tab)

- src/MainWindow.vala
fix #495
keep focus on the terminal when a tab is closed.
> keep terminal focus when tab is closed

- src/Dialogs/UnsafePasteDialog.vala
- src/MainWindow.vala
This also sets the default action to "Do not Paste" (as suggested in the linked issue). Fixes #293 .
> Paste Protection dialog cancels pasting if Escape is pressed

- src/MainWindow.vala
- src/Utils.vala
Not checking this can lead to crashes when a string cannot be escaped, for example if the string is the contents of an open Vim window. As such, when doing "select all" while having Vim open would crash the terminal as it tried to check if the new selection contains a link.
> Catch Uri.unescape_string returning null

- src/MainWindow.vala
- src/Widgets/TerminalWidget.vala
Fix #544 . The solution adopted was to kill the current shell child process and create a new one using the same terminal. 
I'm not sure if the Reload option was added in the correct place. It seems all exiting options come from DynamicNotebook, so I just added an extra option after a tab is created.
> Add Reload item to terminal tabs.

- src/MainWindow.vala
- src/Widgets/TerminalWidget.vala
Fixes #583 
Fixes #567 
Replaces #568 
* Run update on new tab, switch tab, close tab and contents changed
* Do not use terminal.window_title
> Refactor name check and title update so works with custom prompt

- src/MainWindow.vala
Reinstate fix that was inadvertantly reverted in final version of c3e36fb2ab64c18028ff2b4a6da5bfb2171c1c04
> Update window title on switch page

- src/MainWindow.vala
Change the tooltip back after being changed by Granite.  Not an elegant solution - is there a better one without changing Granite?
> Ensure tab tooltip shows full path

- src/MainWindow.vala
Fixes #588
Somehow it seems to be not possible to initialize two properties to the same value in one lines. I am not sure if this is a limitation of the Vala compiler or if it's me not understanding the semantics of the syntax correctly.
> Fix regression of #585

- src/MainWindow.vala
This stops critical warnings like:
`(io.elementary.code:100977): Gtk-CRITICAL **: 13:21:33.248: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkNotebook` 
on startup
> Stop critical warnings on startup

- src/MainWindow.vala
When there's only one tab, dragging the tab out and back of the notebook area closes the window because of the check in `on_tab_removed`. Instead, only run the check if the function is not called during a drag and do it afterwards when the `drag_end` signal is emitted.
fixes #577.
> MainWindow: Don't Close the Window During Drag and Drop

- src/MainWindow.vala
Fixes #603 
If closing a tab results in the window closing then the details of that tab (including zoom level) should be saved and restored.
> Save and restore last tab closed

- config.vala.in
- meson.build
- src/Application.vala
Provides the directory where the locales are actually installed.
We are [packaging this](https://github.com/NixOS/nixpkgs/pull/130380#issuecomment-895720580) in NixOS, and due to NixOS 's special `localedir`, we cannot apply the translations without this patch.
Thanks in advance for reviewing this :-)
> l10n: Correctly setup the locales

- src/MainWindow.vala
Fixes #614 
Locale independent functions are use to convert zoom settings to and from double to string.
> Use locale independent conversion for zoom

- data/io.elementary.terminal.appdata.xml.in
- src/MainWindow.vala
Fixes #617 
* Use `<Shift><Control>R` as preferred accel for reload action
* Retain `F5` as alternative but modify it with `<Shift>` to avoid clashes
Other solutions are possible but this seems the simplest non-destructive one.
> Avoid F5 shortcut clash with some foreground processes

- src/MainWindow.vala
This allows `Alt+[1-9]` to be handled by applications such as WeeChat (with just one tab open) while functioning like before when another is opened (previously `Alt+1` and `Alt+9` were completely unusable within WeeChat hindering its featureset).
Without more than one tab open it doesn't make sense attempting to handle the `Alt+1` and `Alt+9` shortcut actions anyway.
> MainWindow: Switch tab with Alt+[1-9] when there are at least 2 tabs

- data/Application.css
- meson.build
- src/Dialogs/ColorPreferencesDialog.vala
- src/MainWindow.vala
- src/Themes.vala
- src/Widgets/TerminalWidget.vala
Pulled from #552 
Fixes #418 
Potentially address #39 
Potentially addresses #71
Potentially address #501 
Partially addresses #507 
Potentially address #632 
Additional work:
> Add a custom theme dialog

- data/io.elementary.terminal.gschema.xml
Make sure the custom theme isn't the same thing as the dark theme by default
> GSchema: change custom theme default values to Solarized Dark

- data/io.elementary.terminal.gschema.xml
- src/MainWindow.vala
- src/Themes.vala
- src/Widgets/TerminalWidget.vala
Fixes #618
The UX is copied from #546 
The mechanism for getting the widgets to update their color scheme when the system default changes is somewhat non-obvious (the application settings are signaled to have changed even though they haven't) so as to make this work with the existing mechanism which requires an application settings change.
> Add "Follow System Style" toggle

- meson_options.txt
Grepping this does not return other result for me, probably no longer useful after #675 (yeah we carry this option in nixpkgs since initial packaging so it is really nice to see we can drop this)
> build: Drop unused ubuntu-bionic-patched-vte option

- src/Widgets/TerminalWidget.vala
Fixes #689 
`fc` is a BASH builtin than we can use as an alternative to `history` that will give us some more consistently formatted results so we don't accidentally end up with other bits of `history` output in our notifications.
> Use fc to get previous command

- src/MainWindow.vala
_Control + PageUp_ and _Control + PageDown_ are common shortcuts to switch between tabs.
There are used by other apps such as Web, Chrome and Firefox, and other terminals like gnome-terminal.
This commit add these shortcuts to io.elementary.terminal.
> Add shortcuts Ctrl + PageUp and Ctrl + PageDown to switch between tabs

- src/Application.vala
- src/tests/Application.vala
We where depending on the binary exiting to unexport the interface, however, the test suite launch a instance per test, and they where failing because of the interface being already registred, and ending in false positives.
the suite where ammended to check for the application exit status too and fail if not 0.
> Application: Properly Unexport the DBus Interface on Exit

- src/MainWindow.vala
This prevents this particular shortcut for interfering with the selection of text in some advanced TUI text editors like micro (fixes #676). 
We already have the following shortcuts for changing tabs:
ctrl + tab, ctrl + shift + tab;
ctrl + pgup, ctrl + pgdown;
ctrl + shift + pgup, ctrl + shift + pgdn;
These are all consistent with both Files and Web. Terminal should follow this standard as well.
> Remove ctrl + shift + left / right for tab switching

- src/Application.vala
Fixes #681: you can start Terminal minimized. Handy when starting 
Terminal with a command at login time, but you don't want a window to be
displayed.
> Add option to start minimized

- .github/workflows/ci.yml
- src/Dialogs/ColorPreferencesDialog.vala
- src/MainWindow.vala
- src/Widgets/SettingsPopover.vala
- src/meson.build
move the settings menu popover, and related functions to they own class.
the settings object is now, also used to keep the state between the widgets synchronized, and the actions provided by it make the new class mostly self-contained, only needing a single signal to indicate the window that the theme dialog should be shown.
> Add `SettingsPopover` Class

- src/Widgets/SettingsPopover.vala
Fixes #596 
A possible refinement of this would be to only show this option when the relevant system settings mean that an audible or visual notification will be made on an event alert.
> Expose audible-bell setting in Settings Menu

- src/MainWindow.vala
It looks like Terminal hasn't build in daily since #699 
Something with setting accels is causing tests to pass in CI here, but not during the launchpad build: https://launchpadlibrarian.net/695825095/buildlog_ubuntu-noble-amd64.io.elementary.terminal_6.1.2+r2374+pkg87~daily~ubuntu24.04.1_BUILDING.txt.gz
`stdout: 14: UNKNOWN: (/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/src/io.elementary.terminal.tests.application:8441): Gtk-WARNING **: 19:05:25.710: Unable to parse accelerator 'GVariant': ignored request to install 8 accelerators`
It looks like we null terminate the other arrays, so I'm guessing that's the problem?
> MainWindow: null terminate accel arrays

- src/Application.vala
- src/MainWindow.vala
- src/Widgets/SettingsPopover.vala
- src/Widgets/TerminalWidget.vala
As part of reducing the size of the MainWindow class, these was relying on the current_terminal property to work, however, both key handling and actions goes from the focused widget to the topmost parent. so we can move them to TerminalWidget class without problems.
> MainWindow: Move Actions and Keyboard Handling Related to The View to TerminalWidget

- src/Widgets/TerminalWidget.vala
When the view lost keyboard focus by activating the search action, we stop reciving key releases in the view's key controller, letting the scroll controller activated.
That was making the terminal zoom in/out instead of scrolling in this case.
> TerminalWidget: Stop Scroll Controller When Keyboard Focus is Lost

- data/Application.css
- src/MainWindow.vala
This style class is used to make sure custom colors can use alpha. Otherwise they'll just be overlaying on a solid color background
> Fix transparent background

- src/Widgets/TerminalView.vala
Tiny thing, but we're using `Reload` elsewhere:
https://l10n.elementary.io/search/?q=reload+language%3Aen&sort_by=-priority%2Cposition&checksum=
Originally reported from @edwood-grant on Weblate:
https://l10n.elementary.io/translate/terminal/terminal/en/?checksum=3b7b993be25291d0#comments
> TerminalView: ReLoad→Reload

- src/MainWindow.vala
- src/Widgets/TerminalWidget.vala
Reinsert `show_all ()`
Also changes non-specific name `menu` to more specific `context_menu` to more easily distinguish from MenuButton popover menu.
> Fix empty context menu regression

- data/Application.css
- src/MainWindow.vala
- src/Widgets/TerminalWidget.vala
Needs some CSS here to fix stylesheet bugs, but this will show accelerators. Gotta make the section labels null or we get a weird bug with separator height being forced to match an empty label
> Use Gtk.Menu

- data/Application.css
- src/MainWindow.vala
- src/Widgets/TerminalWidget.vala
This is similar to #751 but based on latest master and more closely following current code to reduce diff (a little).  Code cleanup can be done in separate PR.
Also added custom "accel" menu attribute to the items.  This does not seem to be working with the current version - maybe it ill work in Gtk4?
> Use GLib.MenuModel for context menu

- src/MainWindow.vala
Gdk.Geometry does not exist in Gtk4
> Gtk4Prep - Lose geometry hints

- data/io.elementary.terminal.gschema.xml
- src/Application.vala
- src/MainWindow.vala
- Gtk4 Does not have configure-event
- Follow pattern of Icon Browser (Gtk4) with regards to settings 
- Restore saved state function can just be deleted on porting
- Replaced by settings binding to window properties.
> Gtk4Prep - Handle restoring and syncing window state in Application

- data/Application.css
- src/Widgets/SettingsPopover.vala
GTK4 prep. Adding a provider to a widget is deprecated. Also, in Gtk4 adding a provider to a context doesn't add it to the children of the context, so this was broken
> SettingsPopover: use provider_for_screen for theme buttons

- src/Widgets/TerminalWidget.vala
Extracted from #780  as far as possible.
As the handlers do not share significant code it is clearer to have them separate.
We will not need to keep additional references to the controllers in Gtk4
> Separate button controllers - Gtk4 prep

- src/Widgets/SettingsPopover.vala
- src/Widgets/TerminalWidget.vala
In Gtk4, the terminal zoom actions will be lost (replaced with `add_binding_signal ()` to provide keyboard shortcuts for zooming).  We do not need to use them in SettingsPopover as we already have a reference to the current terminal.
> Gtk4 Prep - SettingsPopover - call terminal zoom functions directly

- src/Dialogs/ColorPreferencesDialog.vala
- src/Widgets/TerminalView.vala
- src/Widgets/TerminalWidget.vala
Small changes in code style of some constructors to more closely follow elementary code style.
- Use construct block
- Move assignments out of constructor function into construction block where possible
> Code Style - 

- src/Widgets/SearchToolbar.vala
Updates the icon name and tooltip text according to the state of the toggleaction.
This makes it easier to see whether the cyclic search is enabled or not.
> Update cyclic search button when toggled

- src/Widgets/TerminalWidget.vala
Fix a regression from #794 that non administrative commands like `apt list --installed` no longer pasted.
> TerminalWidget: Fix non administrative commands not being pasted

- src/Dialogs/UnsafePasteDialog.vala
- src/MainWindow.vala
- src/Widgets/TerminalWidget.vala
This PR removes the dead feature that disables unsafe paste warning while Terminal opens.
---
As far as reading the code of UnsafePasteDialog.vala, this dialog shouldn't appear again while the current Terminal window is alive once if the user clicks "Paste Anyway". However, this isn't working at the moment because the clicked event of the "Paste Anyway" button is treated as a response of UnsafePasteDialog and the `on_ignore ()` method is not triggered at all.
On the other hand, however, I also feels the current "unintentional" behavior that this dialog always appears when pasting administrative commands makes sense too. We can now toggle unsafe paste warning from preferences menu,
so this dead feature is useless. Therefore, I just dropped the dead feature instead of correctly implementing …
> Drop dead feature that disables unsafe paste warning while Terminal opens

- src/Widgets/TerminalWidget.vala
> Provide fallback directory for active shell under test

- src/Widgets/TerminalWidget.vala
Not the cleanest. Can always define "more" dangerous behaviours, depends how much we want to get in the weeds. I need to learn more vala
contains:
Multiple commands: as oneliners chained with ";", "||", "|", "&&", "&"
Admin commands: run0, su, pkexec, who serve similar purpose to sudo and doas. "su -" can do a lot too
Add a space, to avoid false flag if say, it is a word like "visual" that has "su" in it. A command needs a space after it.
Following #799 thought its too a minute change to bug anyone
> Enhance unsafe detection

- data/io.elementary.terminal.appdata.xml.in
- src/Application.vala
- src/MainWindow.vala
Fixes #814 
- New tab added in Application `new-window` action handler
- New window follows size of current window
- New tab follows current working directory of current window
There is scope for improving consistency and DRYing with code handling new windows created by dragging tabs, from the dock and from the commandline but that is left for now.
Code potentially changing the window size by adding a tab was removed as it did not seem appropriate. The window size is already controlled by settings, the user and the window manager.
> Add tab to new window created with <Shift><Ctrl>N

- data/io.elementary.terminal.gschema.xml
- src/Application.vala
- src/MainWindow.vala
This reverts commit 32ff88ecea950d172e65c8cfd7cb86b22800712f.
Fixes #821
No elegant fix was found that worked with Gtk3/X  on OS7.1 so the proposed changes in this commit will have to wait until the Gtk4 port I guess.  The draft Gtk4 port in preparation does not suffer from this issue.
For simplicity, the new window action now creates a window the same size as the window currently in use rather getting from the settings.
> Revert "Gtk4Prep - Handle restoring and syncing window state in App

- src/Dialogs/ForegroundProcessDialog.vala
- src/MainWindow.vala
- src/Widgets/TerminalWidget.vala
Fixes #819 
Fixes #820 
Because we cannot guarantee the state of the terminal if the foreground process is killed (see #824 ) the clear action is ignored when a foreground process is running. Resetting the terminal is OK as the terminal state is reset to something sensible.
There is little difference between the "Reload" action and the "Reset" action. The former starts a new shell process whereas the latter resets the existing one.  Not sure if we need both. Only the latter is shown in the context menu atm.
> Fix clear and reset actions when ongoing foreground process

- src/Widgets/TerminalWidget.vala
Follow up of #823.
https://github.com/elementary/terminal/blob/308191f6f30a013c098051fda06deeaa5943a50c/src/Widgets/TerminalWidget.vala#L77-L78
> Only reset/clear screen when <Shift> is pressed

- src/MainWindow.vala
- src/Widgets/TerminalView.vala
- src/tests/Application.vala
Fixes #834 
Rather than use the native Hdy.TabView select_next_page ()  and select_previous_page () functions, which do not cycle, a custom function is used.
> Cycle tabs with Ctrl+Tab

- po/POTFILES
- src/Utils.vala
- src/Widgets/TerminalWidget.vala
- src/meson.build
- src/tests/UnsafePasteTest.vala
- src/tests/meson.build
Move unsafe paste detection to Utils and add tests
> Tests: add unsafe paste test

- data/io.elementary.terminal.appdata.xml.in
bumping to 7 because we're no longer releasing terminal for OS 6.x
> Metainfo: add 7.0.0 release notes

- src/MainWindow.vala
* Bump license header
* No more `decoration_layout_set` in GTK4
* Explicit expands
* Child property
* More accurate cast, no more `Gtk.Bin`
* ScrolledWindow doesn't take args in GTK4, so use vadjustment property
* Minimize use of Gtk.Clipboard functions that are going away
* Remove `set_visual`. This is I think really old stuff and it's not clear it even does anything for us in GTK3
> MainWindow: GTK4 prep

- src/MainWindow.vala
Fixes #840, with side-effects
The cause of the issue is that the custom title is set to horizontally expand so the headerbar cannot center it on itself.
There is no simple fix to this issue while keeping the same appearance of the search widget as far as I can find. As a compromise, the search widget now has a fixed width which should be sufficient for most search terms and is centered in the headerbar.
BEFORE
AFTER
> Center the title, set min searchentry width

- src/MainWindow.vala
- src/Widgets/TerminalWidget.vala
Partially fixes #698 
Partially fixes #646
When a foreground process is running in a tab, the tab label now shows information about the running process.
To be decided - what information should be shown? Currently it is the basename of the `exe` file from the `/proc/<pid>` directory.
When the foreground process is `screen`, it proved impossible (?) to get the working directory of the screen window currently showing (it show more than one anyway). It is possible to edit the `screenrc` config file to show screen status info in the headerbar and/or within its own windows.
> Change tab label to name of foreground child process

- src/MainWindow.vala
Makes sure to not resize the window when using a long command. Done the same as in Gtk.
> MainWindow: Ellipsize the title label

- src/Widgets/SettingsPopover.vala
Closes #885 
GTK4 prep. Uses a stateful action from Settings.create_action for theme buttons and use CheckButton instead of RadioButton. Can be rebase merged if desired
> SettingsPopover: create ThemeCheckButton and use Settings action

- src/Widgets/SearchToolbar.vala
View hiding whitespace change.
Any other Gtk4 prep needed?
Keeping as draft until pending release goes out
> SearchToolbar: Modernise, prepare for Gtk4

- src/Dialogs/UnsafePasteDialog.vala
Any more prep needed?
Keeping as draft until pending release goes out.
> Unsafepastedialog: Modernise, Gtk4 preparation

- src/Dialogs/ColorPreferencesDialog.vala
Any more prep needed?
Keeping as draft until pending release goes out.
> Colorpreferencesdialog: Modernise/Gtk4prep

- src/Widgets/TerminalView.vala
Little to do here.  DnD stuff has to be done in port. Any more preparation possible?
> TerminalView: Clean/Gtk4 preparation

- src/Application.vala
Some fairly substantive changes around `process-finished` notifications.
TODO (maybe).
Changes need to be made around restoring window size which entail changing the settings schema. These could be done before or during the port and are left for another PR.
@danirabbit When is the correct time to make settings schema changes?
> Application: Gtk4 preparation

- src/Application.vala
- src/MainWindow.vala
Fixes #831
The "process-finished" icon is only added if the tabpage is not selected when the process finishes so we only need remove it when the tabpage is selected.
> Remove tab process-finished icon on select

- src/Widgets/TerminalWidget.vala
Fixes https://github.com/elementary/terminal/issues/876
Closes https://github.com/elementary/terminal/pull/877
URIs **must** escape special characters and Utils.sanitize_path undoes this. Furthermore, there's no other reasons to use  Utils.sanitize_path here -- dropped paths must be absolute. So in conclusion if a file manager does everything correctly, we shouldn't need this. I tested this branch using Dolphin.
> Don't sanitize URI on drop

- src/Utils.vala
- src/tests/UnsafePasteTest.vala
> Only embedded newlines should trigger safe paste warning

- data/meson.build
- data/terminal.metainfo.xml.in
- po/extra/POTFILES
* Rename as `metainfo` and use meson renaming
* add `environment` tag to screenshots
* add `vcs-browser` url
* Mark old release notes as no translate
> Metainfo: rename file, add screenshot env, no translate old releases
